#pragma once

// Public C++ facade for the franka-rust bridge.
// The concrete ABI is generated by cxx from `src/ffi/to_cxx.rs`.

#include "robot_behavior.hpp"

#include <array>
#include <memory>
#include <string>

namespace franka_rust {

using PoseData = robot_behavior::PoseData;
using LoadState = robot_behavior::LoadState;

class FrankaArm : public robot_behavior::Arm<7>,
                  public robot_behavior::JointMotion<7>,
                  public robot_behavior::FlangeMotion {
public:
  std::string version() const override;
  void init() override;
  void shutdown() override;
  void enable() override;
  void disable() override;
  void reset() override;
  void stop() override;
  void emergency_stop() override;
  void clear_emergency_stop() override;
  bool is_moving() override;

  std::string state() override;
  void set_load(const LoadState &load) override;
  std::array<double, 7> get_joint() const override;
  PoseData get_endpoint() const override;

  void move_joint(std::array<double, 7> target) override;
  void move_joint_sync(std::array<double, 7> target) override;
  void move_flange(PoseData target) override;
  void move_flange_sync(PoseData target) override;
};

class FrankaEmika : public FrankaArm {};
class FrankaFR3 : public FrankaArm {};

std::unique_ptr<FrankaEmika> franka_emika_attach(const std::string &ip);
std::unique_ptr<FrankaFR3> franka_fr3_attach(const std::string &ip);

} // namespace franka_rust
